

2022-04-29 09:50:19,845	file name:user_database.py	function name:insert_new_user  ERROR: 	user_ID:1723464345
Traceback (most recent call last):
  File "c:\Users\user\Desktop\mstr_bot\git\mstr-chat-bot\database\user_database.py", line 51, in insert_new_user
    self.cursor.execute(
sqlite3.OperationalError: table sqlite_sequence has no column named ID


2022-04-29 12:56:51,696	file name:user_database.py	function name:insert_new_user  ERROR: 	user_ID:1723464345
Traceback (most recent call last):
  File "c:\Users\user\Desktop\mstr_bot\git\mstr-chat-bot\database\user_database.py", line 52, in insert_new_user
    self.cursor.execute(
sqlite3.OperationalError: table sqlite_sequence has no column named ID


2022-05-05 15:08:04,158	file name:user_database.py	function name:get_triggers_by_name  ERROR: 
Traceback (most recent call last):
  File "c:\Users\user\Desktop\mstr_bot\git\mstr-chat-bot\database\user_database.py", line 125, in get_triggers_by_name
    self.cursor.execute(
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 22988 and this is thread id 24416.


2022-05-05 15:08:15,604	file name:user_database.py	function name:get_triggers_by_name  ERROR: 
Traceback (most recent call last):
  File "c:\Users\user\Desktop\mstr_bot\git\mstr-chat-bot\database\user_database.py", line 125, in get_triggers_by_name
    self.cursor.execute(
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 22988 and this is thread id 24416.


2022-05-05 15:38:23,921	file name:user_database.py	function name:__init__  INFO: Create connection to database: database/bot_database.sqlite


2022-05-05 15:39:52,593	file name:user_database.py	function name:__init__  INFO: Create connection to database: database/bot_database.sqlite


2022-05-05 15:45:21,033	file name:user_database.py	function name:get_triggers_by_name  ERROR: 
Traceback (most recent call last):
  File "c:\Users\user\Desktop\mstr_bot\git\mstr-chat-bot\database\user_database.py", line 125, in get_triggers_by_name
    self.cursor.execute(
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 26812 and this is thread id 3020.


2022-05-05 15:50:51,833	file name:user_database.py	function name:__init__  INFO: Create connection to database: database/bot_database.sqlite


2022-05-05 15:51:13,786	file name:user_database.py	function name:get_triggers_by_name  ERROR: 
Traceback (most recent call last):
  File "c:\Users\user\Desktop\mstr_bot\git\mstr-chat-bot\database\user_database.py", line 125, in get_triggers_by_name
    self.cursor.execute(
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 27980 and this is thread id 16712.


2022-05-05 15:54:21,578	file name:user_database.py	function name:__init__  INFO: Create connection to database: database/bot_database.sqlite


2022-05-05 15:54:33,275	file name:user_database.py	function name:get_triggers_by_name  ERROR: 
Traceback (most recent call last):
  File "c:\Users\user\Desktop\mstr_bot\git\mstr-chat-bot\database\user_database.py", line 125, in get_triggers_by_name
    self.cursor.execute(
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 26536 and this is thread id 28560.


2022-05-05 15:56:36,993	file name:user_database.py	function name:__init__  INFO: Create connection to database: database/bot_database.sqlite


2022-05-05 15:56:36,994	file name:user_database.py	function name:__init__  INFO: Create connection to database: database/bot_database.sqlite


2022-05-05 16:03:07,729	file name:user_database.py	function name:__init__  INFO: Create connection to database: database/bot_database.sqlite


2022-05-05 16:03:07,729	file name:user_database.py	function name:__init__  INFO: Create connection to database: database/bot_database.sqlite


2022-05-05 16:04:44,644	file name:user_database.py	function name:__init__  INFO: Create connection to database: database/bot_database.sqlite


2022-05-05 16:04:44,646	file name:user_database.py	function name:__init__  INFO: Create connection to database: database/bot_database.sqlite


2022-05-05 16:06:00,970	file name:user_database.py	function name:__init__  INFO: Create connection to database: database/bot_database.sqlite


2022-05-05 16:06:00,971	file name:user_database.py	function name:__init__  INFO: Create connection to database: database/bot_database.sqlite


2022-05-05 16:08:56,694	file name:user_database.py	function name:__init__  INFO: Create connection to database: database/bot_database.sqlite


2022-05-05 16:08:56,695	file name:user_database.py	function name:__init__  INFO: Create connection to database: database/bot_database.sqlite


2022-05-05 16:11:50,072	file name:user_database.py	function name:__init__  INFO: Create connection to database: database/bot_database.sqlite


2022-05-05 16:11:50,073	file name:user_database.py	function name:__init__  INFO: Create connection to database: database/bot_database.sqlite


2022-05-05 16:12:14,002	file name:user_database.py	function name:__init__  INFO: Create connection to database: database/bot_database.sqlite


2022-05-05 16:12:14,004	file name:user_database.py	function name:__init__  INFO: Create connection to database: database/bot_database.sqlite


2022-05-05 16:12:42,324	file name:user_database.py	function name:__init__  INFO: Create connection to database: database/bot_database.sqlite


2022-05-05 16:12:42,326	file name:user_database.py	function name:__init__  INFO: Create connection to database: database/bot_database.sqlite


2022-05-05 16:13:26,196	file name:user_database.py	function name:__init__  INFO: Create connection to database: database/bot_database.sqlite


2022-05-05 16:13:26,197	file name:user_database.py	function name:__init__  INFO: Create connection to database: database/bot_database.sqlite


2022-05-05 16:15:48,611	file name:user_database.py	function name:__init__  INFO: Create connection to database: database/bot_database.sqlite


2022-05-05 16:15:48,612	file name:user_database.py	function name:__init__  INFO: Create connection to database: database/bot_database.sqlite


2022-05-05 16:17:13,851	file name:user_database.py	function name:__init__  INFO: Create connection to database: database/bot_database.sqlite


2022-05-05 16:17:13,852	file name:user_database.py	function name:__init__  INFO: Create connection to database: database/bot_database.sqlite


2022-05-05 16:18:31,850	file name:user_database.py	function name:__init__  INFO: Create connection to database: database/bot_database.sqlite


2022-05-05 16:18:31,851	file name:user_database.py	function name:__init__  INFO: Create connection to database: database/bot_database.sqlite


2022-05-05 16:21:22,139	file name:user_database.py	function name:__init__  INFO: Create connection to database: database/bot_database.sqlite


2022-05-05 16:21:22,140	file name:user_database.py	function name:__init__  INFO: Create connection to database: database/bot_database.sqlite


2022-05-11 10:18:59,014	file name:user_database.py	function name:__init__  INFO: Create connection to database: database/bot_database.sqlite


2022-05-11 10:18:59,017	file name:user_database.py	function name:__init__  INFO: Create connection to database: database/bot_database.sqlite


2022-05-11 10:20:20,288	file name:user_database.py	function name:__init__  INFO: Create connection to database: database/bot_database.sqlite


2022-05-11 10:20:20,290	file name:user_database.py	function name:__init__  INFO: Create connection to database: database/bot_database.sqlite


2022-05-11 13:45:58,504	file name:user_database.py	function name:__init__  INFO: Create connection to database: database/bot_database.sqlite


2022-05-11 13:45:58,505	file name:user_database.py	function name:__init__  INFO: Create connection to database: database/bot_database.sqlite


2022-05-11 13:46:38,182	file name:user_database.py	function name:__init__  INFO: Create connection to database: database/bot_database.sqlite


2022-05-11 13:46:38,182	file name:user_database.py	function name:__init__  INFO: Create connection to database: database/bot_database.sqlite


2022-05-11 13:48:52,962	file name:user_database.py	function name:__init__  INFO: Create connection to database: database/bot_database.sqlite


2022-05-11 13:48:52,963	file name:user_database.py	function name:__init__  INFO: Create connection to database: database/bot_database.sqlite


2022-05-16 15:30:22,349	file name:user_database.py	function name:__init__  INFO: Create connection to database: database/bot_database.sqlite


2022-05-16 15:30:22,352	file name:user_database.py	function name:__init__  INFO: Create connection to database: database/bot_database.sqlite


2022-05-16 15:30:25,492	file name:user_database.py	function name:insert_new_user  ERROR: 	user_ID:449977514
Traceback (most recent call last):
  File "c:\Users\user\Desktop\mstr_bot\git\mstr-chat-bot\database\user_database.py", line 53, in insert_new_user
    self.cursor.execute(
sqlite3.OperationalError: table sqlite_sequence has no column named ID
